use-sort:
    sort-type: alph
    sort-direction: asc

header: |
    /**
     * Copyright 2015, Eduardo Trujillo <ed@sellerlabs.com>
     *
     * For the full copyright and license information, please view the LICENSE
     * file that was distributed with this source code.
     *
     * This file is part of the PHP Standards package
     */
